apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tomcat-app"
spec:
  template:
    spec:
      containers:
       - name: tomcat-app
         resources:
           limits:
             memory: 1G
           requests:
             memory: 1G
